---
- name: Fetch OpenBao StatefulSet
  kubernetes.core.k8s_info:
    kind: StatefulSet
    name: openbao
    namespace: "{{ openbao_namespace }}"
    kubeconfig: "{{ kubeconfig_path | default(omit) }}"
  register: openbao_sts_loop

- name: Update fully ready status
  ansible.builtin.set_fact:
    openbao_ha_ready: >-
      {{ (openbao_sts_loop.resources[0].status.readyReplicas | default(0)) ==
         (openbao_sts_loop.resources[0].spec.replicas | default(1)) }}

- name: Unseal and wait
  block:
    - name: Attempt unsealing all current endpoints
      ansible.builtin.include_tasks: unseal.yml

    - name: Wait for pods to become ready or spin up
      ansible.builtin.pause:
        seconds: 5
  when: not openbao_ha_ready | bool
