---
- name: Read k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token
  become: true
  no_log: true

- name: Store kubeconfig path
  ansible.builtin.set_fact:
    kubeconfig_path: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

