---
galaxy_info:
  role_name: docker_registry_setup
  author: freecloudinitiative
  description: Installs lightweight Docker Registry (registry:2) into a K3s cluster.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - kubernetes
    - registry
    - docker
    - k3s

collections:
  - kubernetes.core
