---
ssh_config_default_user: "entelektuelmaganda"
ssh_config_default_identity_file: "~/.ssh/gcp_k3s"

ssh_config_dir: "{{ '~/.ssh' | expanduser }}"
ssh_config_file: "{{ '~/.ssh/config' | expanduser }}"
ssh_known_hosts_file: "{{ '~/.ssh/known_hosts' | expanduser }}"

ssh_config_clean_known_hosts: false
ssh_config_scan_known_hosts: true
ssh_config_strict_host_key_checking: "no"

ssh_hosts: {}
ssh_config_custom_hosts: []
