---
- name: Fetch Kubeconfig and Setup Local K9s
  hosts: "{{ groups['masters'][0] }}"
  gather_facts: false
  become: false
  vars:
    k3s_master_public_ip: "104.198.58.94"
  roles:
    - local-kubeconfig-setup
