[masters]
master-1 master_label=master-1
# master-2 master_label=master-2
# master-3 master_label=master-3

[workers]
worker-1 worker_label=worker-1
worker-2 worker_label=worker-2
worker-3 worker_label=worker-3

[high_memory]
worker-1 worker_label=worker-1

[mid_memory]
worker-2 worker_label=worker-2

[low_memory]
worker-3 worker_label=worker-3
