[master]
master1.local ram=4gb fan=1

[worker1]
worker1.local ram=8gb

[worker2]
worker2.local ram=8gb fan=2

[worker3]
worker3.local ram=4gb fan=1

[worker4]
worker4.local ram=8gb fan=2

[worker5]
worker5.local ram=16gb fan=2

[worker6]
worker6.local ram=16gb fan=2

[workers:children]
worker1
worker2
worker3
worker4
worker5
worker6

[all:children]
master
worker1
worker2
worker3
worker4
worker5
worker6

[high_memory]
worker5.local
worker6.local

[mid_memory]
worker1.local
worker2.local
worker4.local

[low_memory]
worker3.local

[all:vars]
ansible_user=pi
ansible_password={{ password }}
ansible_become_password={{ password }}