[masters]
master-1 master_label=master-1 ansible_host=master1.local

[workers]
worker-1 worker_label=worker-1 ansible_host=worker1.local
worker-2 worker_label=worker-2 ansible_host=worker2.local
worker-3 worker_label=worker-3 ansible_host=worker3.local
worker-4 worker_label=worker-4 ansible_host=worker4.local
worker-5 worker_label=worker-5 ansible_host=worker5.local
#worker-6 worker_label=worker-6 ansible_host=worker6.local

[high_memory]
worker-1 worker_label=worker-1
worker-3 worker_label=worker-3

[mid_memory]
worker-4 worker_label=worker-4

[low_memory]
worker-2 worker_label=worker-2
worker-5 worker_label=worker-5

[all:vars]
ansible_user=pi
ansible_password="{{ pi_ssh_password }}"
ansible_become_password="{{ pi_ssh_password }}"
