---
- name: Configure Local SSH & Clean Known Hosts
  hosts: localhost
  connection: local
  become: false

  vars:
    ssh_config_env: nonprod
    ssh_config_clean_known_hosts: true
    ssh_hosts:
      nonprod-master-1:
        hostname: "{{ k3s_master1_public_ip }}"
        aliases:
          - nonprod-master1
          - np-master1
        cloud: aws
      nonprod-worker-1:
        hostname: "{{ k3s_worker1_public_ip }}"
        aliases:
          - nonprod-worker1
          - np-worker1
        cloud: aws
      nonprod-worker-2:
        hostname: "{{ k3s_worker2_public_ip }}"
        aliases:
          - nonprod-worker2
          - np-worker2
        cloud: aws
      nonprod-worker-3:
        hostname: "{{ k3s_worker3_public_ip }}"
        aliases:
          - nonprod-worker3
          - np-worker3
        cloud: aws
      nonprod-worker-4:
        hostname: "{{ k3s_worker4_public_ip }}"
        aliases:
          - nonprod-worker4
          - np-worker4
        cloud: aws
      nonprod-worker-5:
        hostname: "{{ k3s_worker5_public_ip }}"
        aliases:
          - nonprod-worker5
          - np-worker5
        cloud: aws
      nonprod-worker-6:
        hostname: "{{ k3s_worker6_public_ip }}"
        aliases:
          - nonprod-worker6
          - np-worker6
        cloud: aws

  roles:
    - ssh-config-setup
