---
- name: Pre-setup
  hosts: all
  become: true
  roles:
    # - inventory-validation
    # - raspberry-pi-boot-config # This role will be used in the prod setup
    # - raspberry-pi-cgroups
    - k3s-pre-setup

- name: Setup K3s master nodes
  hosts: masters
  become: true
  gather_facts: true
  roles:
    - k3s-master-setup
    - k3s-fact-gathering

- name: Setup K3s worker nodes
  hosts: workers
  become: true
  gather_facts: true
  vars:
    k3s_node_token: "{{ hostvars[groups['masters'][0]]['k3s_node_token']['content'] | b64decode | trim }}"
  roles:
    - k3s-worker-setup

# - name: Install Kata Containers on high-memory workers
#   hosts: high_memory
#   become: true
#   gather_facts: true
#   roles:
#     - kata-containers

- name: Install K3S Components
  hosts: "{{ groups['masters'][0] }}"
  become: true
  gather_facts: false
  vars:
    k3s_node_token: "{{ hostvars[groups['masters'][0]]['k3s_node_token']['content'] | b64decode | trim }}"
  roles:
    - k3s-node-labeling
    - openbao-setup
    - openbao-secrets-init
    - argocd-setup
    - argocd-bootstrap
    - openbao-ca-secrets
    - k9s-setup

  post_tasks:
    - name: Print NodePort Service URLs and Passwords in JSON format
      ansible.builtin.debug:
        msg:
          argocd: "https://argocd.freecloudinitiative.com"
          grafana: "https://grafana.freecloudinitiative.com"
          prometheus: "https://prometheus.freecloudinitiative.com"
          openbao: "https://vault.freecloudinitiative.com"
          authentik: "https://auth.freecloudinitiative.com"
          alloy: "https://alloy.freecloudinitiative.com"
          traefik_dashboard: "https://traefik.freecloudinitiative.com"
          frontend: "https://freecloudinitiative.com"
          # argocd_password: "{{ argocd_admin_password | default('') }}"
          # grafana_password: "{{ grafana_admin_password | default('') }}"
          # openbao_password: "{{ openbao_token | default(openbao_dev_root_token | default('root')) }}"

# - name: Fetch Kubeconfig and Setup Local K9s
#   hosts: "{{ groups['masters'][0] }}"
#   gather_facts: false
#   become: false
#   roles:
#     - local-k9s-setup
