---
- name: Configure Local SSH & Clean Known Hosts
  hosts: localhost
  connection: local
  become: false

  vars:
    ssh_config_clean_known_hosts: true
    ssh_hosts:
      master-1:  "x.x.x.x"
      # master-2: "x.x.x.x"
      # master-3: "x.x.x.x"
      worker-1:  "x.x.x.x"
      worker-2:  "x.x.x.x"
      worker-3:  "x.x.x.x"

  roles:
    - ssh-config-setup
