---
kyverno_namespace: kyverno
kyverno_stack_dir: "{{ '~/k3s-stack/kyverno' | expanduser }}"
kyverno_release_name: kyverno
kyverno_helm_repo_url: https://kyverno.github.io/kyverno/
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

port_forward_enabled: true
port_forward_address: "0.0.0.0"

kyverno_policy_mode: audit

kyverno_ui_enabled: true
kyverno_ui_enable: "{{ kyverno_ui_enabled }}"
ui_enable: "{{ kyverno_ui_enabled }}"

kyverno_policy_reporter_enabled: "{{ kyverno_ui_enabled }}"
kyverno_policy_reporter_helm_repo_url: "https://kyverno.github.io/policy-reporter"
kyverno_policy_reporter_release_name: "policy-reporter"
kyverno_ui_port_forward_local_port: 8082
kyverno_ui_port_forward_remote_port: 8080
kyverno_ui_service_name: "svc/policy-reporter-ui"

kyverno_policy_require_labels: true
kyverno_policy_disallow_latest_tag: true
kyverno_policy_require_resource_limits: true
kyverno_policy_disallow_privileged: true
