---
galaxy_info:
  role_name: gitea_setup
  author: freecloudinitiative
  description: Installs Gitea Git service via Helm into a K3s cluster.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - kubernetes
    - git
    - gitea
    - helm
    - k3s

collections:
  - kubernetes.core
