---
harbor_namespace: harbor
harbor_release_name: harbor
harbor_helm_repo_url: https://helm.goharbor.io
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
harbor_version: "v2.11.0"

port_forward_enabled: true
port_forward_address: "0.0.0.0"
harbor_port_forward_local_port: 8081
harbor_port_forward_remote_port: 80
harbor_service_name: "svc/harbor-portal"

harbor_node_tier: high-memory

harbor_expose_type: ingress
harbor_external_url: "http://{{ k3s_master_public_ip }}:{{ harbor_port_forward_local_port }}"
