---
gitea_act_runner_namespace: gitea
gitea_act_runner_name: gitea-act-runner
gitea_act_runner_kubeconfig: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"
gitea_act_runner_gitea_url: "http://gitea-http.{{ gitea_act_runner_namespace }}.svc.cluster.local:3000"
gitea_act_runner_registration_token: ""
gitea_act_runner_auto_generate_token: true
gitea_act_runner_image: "gitea/act_runner:latest"
gitea_act_runner_dind_image: "docker:24-dind"
gitea_act_runner_node_tier: "mid-memory"
gitea_act_runner_labels: "ubuntu-latest:docker://node:18-bullseye,ubuntu-22.04:docker://node:18-bullseye"

gitea_act_runner_pvc_enabled: true
gitea_act_runner_pvc_storage_size: "1Gi"
gitea_act_runner_pvc_storage_class: ""
