---
monitoring_namespace: monitoring
loki_stack_dir: "{{ '~/k3s-stack/monitoring' | expanduser }}"
loki_release_name: loki
loki_helm_repo_url: https://grafana.github.io/helm-charts
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

port_forward_enabled: true
port_forward_address: "0.0.0.0"
loki_port_forward_local_port: 3100
loki_port_forward_remote_port: 3100
