---
k9s_version: "v0.32.7"
k9s_install_dir: "/usr/local/bin"
k9s_config_dir: "~/.config/k9s"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
k9s_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "arm"
