---
k9s_version: "v0.32.7"
k9s_install_dir: "/usr/local/bin"
k9s_config_dir: "~/.config/k9s"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
k9s_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "arm"

k9s_namespaces:
  - gitea
  - argocd
  - kube-system
  - monitoring
  - traefik

k9s_config:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: "busybox:1.35.0"
    namespace: "default"
    limits:
      cpu: "100m"
      memory: "100Mi"
  imageScans:
    enable: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70

