---
sealed_secret_namespace: sealed-secrets
sealed_secret_release_name: sealed-secrets
sealed_secret_helm_repo_url: https://bitnami.github.io/sealed-secrets
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

port_forward_enabled: true
port_forward_address: "0.0.0.0"
sealed_secret_node_tier: mid-memory
sealed_secret_controller_name: sealed-secrets
