---
- name: Get CPU temperature
  ansible.builtin.shell: set -o pipefail && vcgencmd measure_temp | cut -d "=" -f2 | tr -d "'"
  args:
    executable: /bin/bash
  changed_when: false
  register: rpi_temp

- name: Display Hostname and Temperature
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }}: {{ rpi_temp.stdout }}"
