---
galaxy_info:
  role_name: k3s_presetup
  author: freecloudinitiative
  description: Prepares a Linux host for K3s installation by disabling swap, updating APT cache, and installing required packages
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kubernetes
    - k3s
    - system
    - presetup
    - swap
