---
k3s_presetup_packages:
  - wireguard-tools
  - open-iscsi
  - nfs-common
  - curl
  - iptables
  - ca-certificates
  - python3-pip
  - python3-setuptools
  - python3-packaging
  - python3-kubernetes
  - python3-jsonpatch
  - python3-yaml
