---
monitoring_namespace: monitoring
otel_stack_dir: "{{ '~/k3s-stack/monitoring' | expanduser }}"
otel_release_name: opentelemetry
otel_helm_repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

port_forward_enabled: true
port_forward_address: "0.0.0.0"
otel_port_forward_local_port: 4317
otel_port_forward_remote_port: 4317
