---
argocd_namespace: argocd
argocd_manifest_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

argocd_node_selector:
  node-tier: mid-memory

argocd_deployments:
  - name: argocd-server
    kind: Deployment
  - name: argocd-repo-server
    kind: Deployment
  - name: argocd-application-controller
    kind: StatefulSet
  - name: argocd-dex-server
    kind: Deployment
  - name: argocd-redis
    kind: Deployment

kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

port_forward_enabled: true
port_forward_address: "0.0.0.0"
argocd_port_forward_local_port: 8080
argocd_port_forward_remote_port: 443
