---
galaxy_info:
  role_name: openbao_setup
  author: freecloudinitiative
  description: Installs OpenBao via Helm into a K3s cluster.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - kubernetes
    - openbao
    - vault
    - secrets
    - security
    - helm
    - k3s

collections:
  - kubernetes.core
