---
monitoring_namespace: monitoring
tempo_stack_dir: "{{ '~/k3s-stack/monitoring' | expanduser }}"
tempo_release_name: tempo
tempo_helm_repo_url: https://grafana-community.github.io/helm-charts
tempo_kubeconfig: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

tempo_port_forward_enabled: true
tempo_port_forward_address: "127.0.0.1"
tempo_port_forward_local_port: 3200
tempo_port_forward_remote_port: 3200
