name: Run Ansible Playbooks

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Select Cloud Provider'
        required: true
        default: 'gcp'
        type: choice
        options:
          - gcp
          - aws
          - azure
      master_1_ip:
        description: 'IP for master-1'
        required: true
        type: string
      master_2_ip:
        description: 'IP for master-2 (optional)'
        required: false
        type: string
      master_3_ip:
        description: 'IP for master-3 (optional)'
        required: false
        type: string
      worker_1_ip:
        description: 'IP for worker-1'
        required: true
        type: string
      worker_2_ip:
        description: 'IP for worker-2'
        required: true
        type: string
      worker_3_ip:
        description: 'IP for worker-3'
        required: true
        type: string

jobs:
  run-playbook:
    uses: freecloudinitiative/.github/.github/workflows/ansible-run.yml@main
    with:
      cloud_provider: ${{ github.event.inputs.cloud_provider }}
      master_1_ip: ${{ github.event.inputs.master_1_ip }}
      master_2_ip: ${{ github.event.inputs.master_2_ip }}
      master_3_ip: ${{ github.event.inputs.master_3_ip }}
      worker_1_ip: ${{ github.event.inputs.worker_1_ip }}
      worker_2_ip: ${{ github.event.inputs.worker_2_ip }}
      worker_3_ip: ${{ github.event.inputs.worker_3_ip }}
    secrets: inherit
