name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-secrets:
    uses: freecloudinitiative/.github/.github/workflows/ansible-validate.yml@main
    secrets: inherit
