---
metallb_namespace: metallb-system
metallb_stack_dir: "{{ '~/k3s-stack/load-balancer' | expanduser }}"
metallb_release_name: metallb
metallb_chart_version: "0.14.9"
metallb_helm_repo_url: https://metallb.github.io/metallb
metallb_kubeconfig: "{{ kubeconfig_path | default('/etc/rancher/k3s/k3s.yaml') }}"

metallb_port_forward_enabled: false
metallb_port_forward_address: "127.0.0.1"
metallb_port_forward_local_port: 9120
metallb_port_forward_remote_port: 9120
metallb_service_name: daemonset/metallb-speaker
